# Generated by Django 3.0.2 on 2020-01-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_auto_20200127_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='creator',
        ),
        migrations.AddField(
            model_name='url',
            name='creator_ip',
            field=models.CharField(default='0.0.0.0', max_length=15),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
