# Generated by Django 3.0.2 on 2020-01-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0003_auto_20200127_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='creator_ip',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
