# Generated by Django 3.0.2 on 2020-01-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0004_auto_20200127_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='last_redirect_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
